sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8
  
before_install:
  # installing newer docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # installing the faas-cli
  - curl -sSL https://cli.openfaas.com | sudo sh
  - docker swarm init
  - chmod +x ./ci-setup.sh
  #- chmod +x ./deploy_stack.sh
  - git clone https://github.com/openfaas/faas && cd faas && ./deploy_stack.sh --no-auth 
  - ./../ci-setup.sh
  - cd ./hello-java

# script:
#   - yarn test

after_script:
  - docker swarm leave -f

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    faas-cli push -f hello-java.yml;
    fi
  # you can deploy to a dev or prod (whatever) environment at this stage